drivers: misc: mediatek: task_turbo: add missing type specifier
../drivers/misc/mediatek/task_turbo/task_turbo.h:16:8: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
extern sched_set_cpuprefer(pid_t pid, unsigned int prefer_type);
~~~~~~ ^
int
1 error generated.

Signed-off-by: CloudedQuartz <ayan.pande06@gmail.com>