drivers: mediatek: extcon: add missing function prototypes
../drivers/misc/mediatek/extcon/extcon-mtk-usb.c:157:20: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void mt_usb_connect()
                   ^
                    void
../drivers/misc/mediatek/extcon/extcon-mtk-usb.c:164:23: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void mt_usb_disconnect()
                      ^
                       void
2 errors generated.

Signed-off-by: CloudedQuartz <ayan.pande06@gmail.com>