drivers: media: v4l2: remove unused variable
../drivers/media/platform/mtk-vcodec/mtk_vcodec_dec.c:982:27: error: variable 'vb2_v4l2' set but not used [-Werror,-Wunused-but-set-variable]
                struct vb2_v4l2_buffer *vb2_v4l2 = NULL;
                                        ^
1 error generated.

Signed-off-by: CloudedQuartz <ayan.pande06@gmail.com>