drivers: mtk: freqhopping: fix -Wvoid-pointer-to-int-cast warning
../drivers/misc/mediatek/freqhopping/fhctl_new/clk-fhctl-mcupm.c:308:6: error: cast to smaller integer type 'unsigned int' from 'void *' [-Werror,-Wvoid-pointer-to-int-cast]
                        + (unsigned int)match_data->reg_tr;
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

- uintptr_t is used for pointer arithmetic

Signed-off-by: CloudedQuartz <ayan.pande06@gmail.com>