drivers: imgsensor: lyriq_ov50a: add missing type specifier
../drivers/misc/mediatek/imgsensor/src/mt6885/../common/v1_1/mot_lyriq_ov50a_mipi_raw/mot_ov50a_eeprom.c:71:8: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
extern adaptor_i2c_wr_seq_p8(struct IMGSENSOR_I2C_CFG *pi2c_cfg,
~~~~~~ ^
int
1 error generated.

Signed-off-by: CloudedQuartz <ayan.pande06@gmail.com>