drivers: tee: MobiCoreDriver: add missing function prototype
../drivers/tee/gud/500/MobiCoreDriver/hwkm.c:28:29: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
static int hwkm_open_session()
                            ^
                             void
1 error generated.

Signed-off-by: CloudedQuartz <ayan.pande06@gmail.com>